### ISSUE TITLE
Model 6.0 PSD 01 Publication Checklist

### ISSUE THREAD

**Issue by cdmgtri** [niemopen/niem-model#73]
## Changes

- [ ] Check issues for [6.0 PSD 01 milestone](https://github.com/niemopen/niem-model/issues?q=is%3Aissue+milestone%3A6.0-psd01) have been closed
- [ ] Check [pull requests](https://github.com/niemopen/niem-model/pulls) have been closed
- [ ] Sync with NDR updates
  - [ ] Check [structures schema](https://github.com/niemopen/niem-naming-design-rules/blob/dev/niem-ndr.md#appendix-b-structures-namespace) is current
  - [ ] Check [appinfo schema](https://github.com/niemopen/niem-naming-design-rules/blob/dev/niem-ndr.md#appendix-c-appinfo-namespace) is current
  - [ ] Get the [latest NDR Schematron rules](https://github.com/niemopen/niem-naming-design-rules/tree/dev)
- [ ] Check other utility schemas are current

## Schemas

- [ ] Check schema version attributes correspond to current stage (`version="psd01"`)
- [ ] Check XML schema validation in Oxygen
- [ ] Check XML schema validation in XMLSpy
  - *Oxygen doesn't validate `xsi:schemaLocation` values*
- [ ] Check NDR Schematron rule conformance in Oxygen
  - *See https://niem.github.io/reference/tools/oxygen/ndr/ for more*

## Documentation

- [ ] Update documentation spreadsheet
- [ ] Update codes spreadsheet
- [ ] Update changelog spreadsheet
- [ ] Update CSVs
- [ ] Update Readme

## Other artifacts

- [ ] Check `xsd/xml-catalog.xml` has current URIs and relative paths
- [ ] Check `json-ld/context.json` has current prefixes and uris

## Specification body

- [ ] **Date**: Update the edit date
  - [ ] Intro, under the title and stage
  - [ ] Intro, *Citation Format*
- [ ] **TOC**: Update the Table of Contents
- [ ] **Related Work**: Update superseded and related specifications in Intro
- [ ] **People**: Update the list of people in special thanks and participants
  - [ ] *Appendix C.1 Special Thanks*
  - [ ] *Appendix C.2 Participants*
- [ ] **Pull request milestone**: *Appendix D. Revision History* - Add a row to the table for pull requests from the latest milestone

## Review

- [ ] Send to NBAC and NTAC co-chairs, NBAC secretary, and OASIS reps for first pass
- [ ] Sent to full NBAC, NTAC, Harmonization SC, and any Domain SC OASIS mailing lists for review
  - *Email to include the following:*
    - link to issues resolved in the latest milestone
     - Call for objections: If no objections received by (date), the working draft will be recommended to the PGB for vote as the next stage
- [ ] Address issues and confirm changes

## PGB Vote

- [ ] NBAC notifies the PGB via the [PGB mailing list](mailto:niemopen-pgb@lists.oasis-open.org) of their recommendation to approve the working draft as 6.0 PSD 01
  - *Email to include the following:*
    - title, version, and GitHub "Download Zip" link
    - link to issues resolved in the latest milestone
    - ~comment resolution log CSV if a Public Review has been held~ - *not applicable*
    - list of non-material changes made since the last approved PSD (if applicable) and an affirmation that the TSC judges the changes to be non-material
- [ ] PGB notifies the NIEMOpen community via the main [NIEMOpen mailing list](mailto:niemopen@lists.oasis-open.org) at least 14 days in advance of the vote or call
- [ ] PGB holds a [Full Majority Vote](https://www.oasis-open.org/policies-guidelines/oasis-defined-terms-2018-05-22/#dFullMajority) via a consensus call or a [poll](https://lists.oasis-open-projects.org/g/niemopen-pgb/addpoll) that is open for at least 3 days
  - *More than 50% of all eligible voters must vote "yes"*
- [ ] PGB submits a request to OASIS to [publish the PSD](https://www.oasis-open.org/form-publish-a-draft-document/)

## Followup

- [ ] Maintainers follow up with OASIS over any non-material changes required for publication
- [ ] Maintainers tag the new commit (`6.0-psd01`)
- [ ] Maintainers publish the new commit as a GitHub release
- [ ] Maintainers update home page announcement banner and the Release pages on https://niem.github.io
